apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-dados
spec:
  acessModes:
    ReadWriteOnce
  resources:
    request:
      storage: 10Gi
  StogageClassName: standard-rwo

---
apiVersion: apps/v1
Kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        image: Paulo/projeto-db:1.0
        args:
        - "--ignore-db-dir = lost+found"
        imagePullPolicy: always
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql

        volumeMounts:
        - name: mysql-dados
          mountPath: /var/lib/mysql/
      volumes:
        - name: mysql-dados
          persistenteVolumeClaim: 
            ClaimName: mysql-dados
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    app: php
spec:
  replicas: 6
  selector:
    matchLabels:
      app: php
  template: 
    metadata:
      labels:
        app: php
    spec:
      containers:
        - name : php
          image: Paulo/projeto-back:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
