FROM php:7.4-apache

WORkDIR /var/www/html

COPY index.php /var/www/htlm/
COPY conexao.php /var/www/htlm/

RUN apt-get update && apt-get install -y \
        libfreetype6-dev\
        libjpeg62-turbo-dev\
        libpng-dev\
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd \
    && docker-php-ext-install pdo_mysql \
    && docker-php-ext-install mysqli

EXPOSE 80
